version: '3.1'
services:
  gateway:
    build: ./gateway
    image: fursov231/ewm-gateway
    container_name: gateway_container
    ports:
      - "8081:8081"
    depends_on:
      - ewm-service
    environment:
      EWM_SERVER_URL: http://server:9090

  stats-server:
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine
    container_name: pg_stats_container
    ports:
      - "6542:5433"
    volumes:
      - /var/lib/postgresql/data/stats/
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  ewm-service:
    build: ./ewm
    image: fursov231/ewm-service
    container_name: ewm_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db

  ewm-db:
    image: postgres:14-alpine
    container_name: pg_ewm_container
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/ewm/
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
