version: '3.1'
services:
  ewm-db:
    image: postgres:14-alpine
    container_name: pg_ewm_container
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/ewm
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  stats-db:
    image: postgres:14.5-alpine
    container_name: pg_stats_container
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/stats/
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  ewm-server:
    build: ./ewm
    image: fursov231/ewm-service
    container_name: ewm_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
      STATS_URL: http://stats-server:9090

  stats-server:
    build: ./statistics
    image: fursov231/stats-service
    container_name: stats-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats




